### PR TITLE
CoffeeScript -> JS

### PR DESCRIPTION
**Pull request by TimvdLippe**
This PR updates all coffeescript files to JS ES6 to be compatible with Hubot 3.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Friendly ping @jabbink

**Comment by TimvdLippe** [comment]
@jabbink This is the last package blocking https://github.com/WISVCH/florriebot/pull/113 Could you take a look soon? Thanks!

**Comment by jabbink** [comment]
Redone in 7b1cc27036de90a4649149a799b671e8e01b6a05 as this repo was behind a couple of commits.

Feel free to double-check. If everything is okay, I'll publish this version to npm and close this pr.

**Comment by TimvdLippe** [comment]
Seems fine to me! Will update the florriebot PR tomorrow and then we can
merge :)

**Pull request closed without merging**
